repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: python -m coverage run -m unittest discover src/tests
        language: system
        pass_filenames: false
-   repo: local
    hooks:
      - id: coverage
        name: run coverage
        entry: python -m coverage html
        language: system
        pass_filenames: false
